import { Terminal, Route, RouteStop, TransferHub } from '@/types/transit';

/**
 * Seed data definitions for the Philippine transit knowledge base.
 * Focus corridors:
 * - Southern Luzon <-> Metro Manila (Lucena, Batangas, Lipa, Calamba/Turbina, Santa Rosa <-> Alabang, PITX, Buendia, Cubao)
 * - Major provincial bus operators: JAC Liner, DLTB Co., JAM Liner, ALPS The Bus, LLI
 * - Metro Manila transit spine: MRT-3, LRT-1, LRT-2, EDSA Carousel Busway
 * - Connecting corridors: Buendia -> Ayala / SM Makati, PITX -> One Ayala, Alabang -> One Ayala
 */

export const SEED_TERMINALS: Terminal[] = [
  // --- Southern Luzon Corridors ---
  {
    id: 'term_lucena_grand',
    name: 'Lucena Grand Central Terminal',
    city: 'Lucena City',
    province: 'Quezon',
    latitude: 13.9482,
    longitude: 121.6247,
    aliases: [
      'Lucena',
      'Lucena Grand',
      'LGCT',
      'Grand Central Lucena',
      'Lucena Terminal',
      'Quezon Grand Terminal',
      'Lucena City',
    ],
  },
  {
    id: 'term_batangas_grand',
    name: 'Batangas City Grand Terminal',
    city: 'Batangas City',
    province: 'Batangas',
    latitude: 13.785,
    longitude: 121.0717,
    aliases: [
      'Batangas',
      'Batangas Grand',
      'Batangas Grand Terminal',
      'Batangas City',
      'Batangas Port Connector',
      'Batangas Terminal',
    ],
  },
  {
    id: 'term_lipa_sm',
    name: 'SM City Lipa Grand Terminal',
    city: 'Lipa City',
    province: 'Batangas',
    latitude: 13.9416,
    longitude: 121.1631,
    aliases: [
      'Lipa',
      'SM Lipa',
      'Lipa Grand Terminal',
      'Lipa City',
      'Lipa Bus Stop',
    ],
  },
  {
    id: 'term_turbina_calamba',
    name: 'Turbina Bus Terminal (Calamba)',
    city: 'Calamba',
    province: 'Laguna',
    latitude: 14.1843,
    longitude: 121.1444,
    aliases: [
      'Turbina',
      'Turbina Calamba',
      'Calamba Turbina',
      'Turbina Bus Stop',
      'SLEX Turbina',
    ],
  },
  {
    id: 'term_calamba_sm',
    name: 'SM City Calamba Central Terminal',
    city: 'Calamba',
    province: 'Laguna',
    latitude: 14.2057,
    longitude: 121.1555,
    aliases: [
      'Calamba',
      'SM Calamba',
      'Calamba Central Terminal',
      'Calamba Crossing',
    ],
  },
  {
    id: 'term_sta_rosa_balibago',
    name: 'Balibago Complex Terminal',
    city: 'Santa Rosa',
    province: 'Laguna',
    latitude: 14.2934,
    longitude: 121.1091,
    aliases: [
      'Balibago',
      'Sta Rosa',
      'Santa Rosa',
      'Balibago Complex',
      'Target Balibago',
    ],
  },

  // --- Southern Metro Manila Gateways ---
  {
    id: 'term_alabang_vtx',
    name: 'VTX Starmall Alabang Terminal',
    city: 'Muntinlupa',
    province: 'Metro Manila',
    latitude: 14.4173,
    longitude: 121.045,
    aliases: [
      'Alabang',
      'Starmall Alabang',
      'VTX',
      'Vista Terminal Exchange',
      'South Station Alabang',
      'Alabang South Station',
      'Starmall',
    ],
  },
  {
    id: 'term_pitx',
    name: 'Parañaque Integrated Terminal Exchange (PITX)',
    city: 'Parañaque',
    province: 'Metro Manila',
    latitude: 14.5097,
    longitude: 120.9922,
    aliases: [
      'PITX',
      'Paranaque Integrated Terminal',
      'Coastal Mall Terminal',
      'Parañaque Terminal',
      'PITX Terminal',
      'PITX Gate 10',
    ],
  },
  {
    id: 'term_buendia_gil_puyat',
    name: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    city: 'Pasay',
    province: 'Metro Manila',
    latitude: 14.5542,
    longitude: 120.9972,
    aliases: [
      'Buendia',
      'Gil Puyat',
      'Buendia Taft',
      'JAC Liner Buendia',
      'DLTB Buendia',
      'JAM Buendia',
      'Pasay Buendia',
      'Buendia Bus Terminal',
      'Taft Buendia',
    ],
  },

  // --- Makati CBD & Core Hubs ---
  {
    id: 'term_ayala_mrt',
    name: 'MRT-3 Ayala Station / SM Makati / One Ayala',
    city: 'Makati',
    province: 'Metro Manila',
    latitude: 14.5492,
    longitude: 121.028,
    aliases: [
      'SM Makati',
      'Ayala',
      'One Ayala',
      'Ayala Center',
      'Makati CBD',
      'Ayala MRT',
      'Glorietta',
      'Greenbelt',
      'Ayala Avenue',
      'One Ayala Terminal',
    ],
  },
  {
    id: 'term_cubao_bus',
    name: 'Cubao Bus Terminals (EDSA Araneta)',
    city: 'Quezon City',
    province: 'Metro Manila',
    latitude: 14.6225,
    longitude: 121.0536,
    aliases: [
      'Cubao',
      'Araneta Center Cubao',
      'Cubao Bus Terminal',
      'EDSA Cubao',
      'DLTB Cubao',
      'JAC Liner Cubao',
      'ALPS Cubao',
      'Five Star Cubao',
      'Farmers Cubao',
    ],
  },

  // --- Rail Stations (MRT-3) ---
  {
    id: 'term_mrt3_north_ave',
    name: 'MRT-3 North Avenue Station',
    city: 'Quezon City',
    province: 'Metro Manila',
    latitude: 14.6531,
    longitude: 121.0322,
    aliases: [
      'North Ave',
      'North Avenue',
      'TriNoma MRT',
      'SM North MRT',
      'MRT North Ave',
    ],
  },
  {
    id: 'term_mrt3_quezon_ave',
    name: 'MRT-3 Quezon Avenue Station',
    city: 'Quezon City',
    province: 'Metro Manila',
    latitude: 14.6427,
    longitude: 121.0384,
    aliases: ['Quezon Ave MRT', 'Centris MRT', 'MRT Quezon Ave'],
  },
  {
    id: 'term_mrt3_ortigas',
    name: 'MRT-3 Ortigas Station',
    city: 'Mandaluyong',
    province: 'Metro Manila',
    latitude: 14.5878,
    longitude: 121.0567,
    aliases: [
      'Ortigas MRT',
      'SM Megamall MRT',
      'Robinsons Galleria MRT',
      'Ortigas Station',
      'Ortigas',
    ],
  },
  {
    id: 'term_mrt3_shaw',
    name: 'MRT-3 Shaw Boulevard Station',
    city: 'Mandaluyong',
    province: 'Metro Manila',
    latitude: 14.5811,
    longitude: 121.0534,
    aliases: [
      'Shaw MRT',
      'Shaw Boulevard',
      'Shangri-La MRT',
      'Starmall EDSA MRT',
    ],
  },
  {
    id: 'term_mrt3_guadalupe',
    name: 'MRT-3 Guadalupe Station',
    city: 'Makati',
    province: 'Metro Manila',
    latitude: 14.5673,
    longitude: 121.0456,
    aliases: ['Guadalupe MRT', 'Guadalupe', 'Guadalupe Ferry Station'],
  },
  {
    id: 'term_mrt3_buendia',
    name: 'MRT-3 Buendia Station',
    city: 'Makati',
    province: 'Metro Manila',
    latitude: 14.5541,
    longitude: 121.0345,
    aliases: ['MRT Buendia', 'Buendia EDSA', 'Buendia MRT Station'],
  },
  {
    id: 'term_mrt3_taft_ave',
    name: 'MRT-3 Taft Avenue Station',
    city: 'Pasay',
    province: 'Metro Manila',
    latitude: 14.5376,
    longitude: 121.0014,
    aliases: [
      'MRT Taft',
      'Taft Ave MRT',
      'Pasay Rotonda MRT',
      'Taft Avenue MRT',
      'EDSA Taft MRT',
    ],
  },

  // --- Rail Stations (LRT-1) ---
  {
    id: 'term_lrt1_fpj',
    name: 'LRT-1 Fernando Poe Jr. (Roosevelt) Station',
    city: 'Quezon City',
    province: 'Metro Manila',
    latitude: 14.6575,
    longitude: 121.0211,
    aliases: [
      'FPJ LRT',
      'Roosevelt LRT',
      'Fernando Poe Jr',
      'Muñoz LRT',
      'Munoz',
    ],
  },
  {
    id: 'term_lrt1_monumento',
    name: 'LRT-1 Monumento Station',
    city: 'Caloocan',
    province: 'Metro Manila',
    latitude: 14.6542,
    longitude: 120.9839,
    aliases: ['Monumento LRT', 'Monumento', 'Caloocan Monumento'],
  },
  {
    id: 'term_lrt1_djose',
    name: 'LRT-1 Doroteo Jose Station',
    city: 'Manila',
    province: 'Metro Manila',
    latitude: 14.6053,
    longitude: 120.9821,
    aliases: ['Doroteo Jose', 'D. Jose LRT', 'Recto Transfer LRT1'],
  },
  {
    id: 'term_lrt1_central',
    name: 'LRT-1 Central Terminal Station',
    city: 'Manila',
    province: 'Metro Manila',
    latitude: 14.5928,
    longitude: 120.9815,
    aliases: ['Central Terminal', 'Lawton LRT', 'Manila City Hall LRT'],
  },
  {
    id: 'term_lrt1_edsa',
    name: 'LRT-1 EDSA Station',
    city: 'Pasay',
    province: 'Metro Manila',
    latitude: 14.5388,
    longitude: 121.0006,
    aliases: ['LRT EDSA', 'EDSA LRT', 'Pasay Rotonda LRT', 'LRT-1 EDSA'],
  },
  {
    id: 'term_lrt1_baclaran',
    name: 'LRT-1 Baclaran Station',
    city: 'Pasay',
    province: 'Metro Manila',
    latitude: 14.5342,
    longitude: 120.9983,
    aliases: ['Baclaran LRT', 'Baclaran', 'Redemptorist LRT'],
  },
  {
    id: 'term_lrt1_dr_santos',
    name: 'LRT-1 Dr. Santos (Sucat) Station',
    city: 'Parañaque',
    province: 'Metro Manila',
    latitude: 14.4967,
    longitude: 120.9892,
    aliases: ['Dr. Santos LRT', 'Sucat LRT', 'LRT Dr Santos'],
  },

  // --- Rail Stations (LRT-2) ---
  {
    id: 'term_lrt2_recto',
    name: 'LRT-2 Recto Station',
    city: 'Manila',
    province: 'Metro Manila',
    latitude: 14.6036,
    longitude: 120.9836,
    aliases: ['Recto LRT', 'C.M. Recto LRT', 'Isetann Recto'],
  },
  {
    id: 'term_lrt2_antipolo',
    name: 'LRT-2 Antipolo Station',
    city: 'Antipolo',
    province: 'Rizal',
    latitude: 14.6253,
    longitude: 121.1214,
    aliases: ['Antipolo LRT', 'Masinag LRT', 'SM Masinag'],
  },
];

export const SEED_ROUTES: Route[] = [
  // --- Provincial Buses: Southern Luzon <-> Metro Manila ---
  {
    id: 'route_jac_lucena_buendia',
    name: 'JAC Liner: Lucena <-> Buendia (via ACTEX / SLEX)',
    mode: 'bus',
    operator: 'JAC Liner',
    frequency: 'Every 20-30 mins (24/7)',
    firstTrip: '02:00',
    lastTrip: '23:30',
  },
  {
    id: 'route_dltb_lucena_buendia',
    name: 'DLTB: Lucena <-> Buendia (via SLEX)',
    mode: 'bus',
    operator: 'DLTB Co.',
    frequency: 'Every 30-45 mins',
    firstTrip: '03:00',
    lastTrip: '22:00',
  },
  {
    id: 'route_dltb_lucena_pitx',
    name: 'DLTB: Lucena <-> PITX (via SLEX)',
    mode: 'bus',
    operator: 'DLTB Co.',
    frequency: 'Every 30-45 mins',
    firstTrip: '03:30',
    lastTrip: '21:30',
  },
  {
    id: 'route_jac_lucena_cubao',
    name: 'JAC Liner: Lucena <-> Cubao (via C5 / EDSA)',
    mode: 'bus',
    operator: 'JAC Liner',
    frequency: 'Every 30-60 mins',
    firstTrip: '03:00',
    lastTrip: '21:00',
  },
  {
    id: 'route_jam_batangas_buendia',
    name: 'JAM Liner: Batangas Grand Terminal <-> Buendia (via STAR / SLEX)',
    mode: 'bus',
    operator: 'JAM Liner',
    frequency: 'Every 20-30 mins',
    firstTrip: '03:00',
    lastTrip: '22:00',
  },
  {
    id: 'route_alps_batangas_pitx',
    name: 'ALPS: Batangas Grand Terminal <-> PITX (via STAR / Cavitex)',
    mode: 'bus',
    operator: 'ALPS The Bus',
    frequency: 'Every 30 mins',
    firstTrip: '03:30',
    lastTrip: '21:30',
  },
  {
    id: 'route_alps_batangas_cubao',
    name: 'ALPS: Batangas Grand Terminal <-> Cubao EDSA',
    mode: 'bus',
    operator: 'ALPS The Bus',
    frequency: 'Every 45 mins',
    firstTrip: '04:00',
    lastTrip: '21:00',
  },
  {
    id: 'route_calamba_buendia',
    name: 'LLI / Saint Rose: Calamba / Turbina <-> Buendia',
    mode: 'bus',
    operator: 'LLI Bus',
    frequency: 'Every 15-20 mins',
    firstTrip: '04:00',
    lastTrip: '22:00',
  },

  // --- Metro Manila Corridors & Transfers ---
  {
    id: 'route_jeep_buendia_ayala',
    name: 'Gil Puyat Jeepney / Bus: Buendia (Taft) <-> Ayala Ave / SM Makati',
    mode: 'jeepney',
    operator: 'Makati Commuter Services',
    frequency: 'Every 3-5 mins (24/7)',
    firstTrip: '04:00',
    lastTrip: '23:59',
  },
  {
    id: 'route_edsa_carousel',
    name: 'EDSA Carousel Busway',
    mode: 'bus',
    operator: 'EDSA Busway Consortium',
    frequency: 'Every 3-5 mins (24/7 Continuous)',
    firstTrip: '00:00',
    lastTrip: '23:59',
  },
  {
    id: 'route_bus_alabang_ayala',
    name: 'Express Bus: Alabang (VTX) <-> One Ayala / SM Makati',
    mode: 'bus',
    operator: 'HM Transport',
    frequency: 'Every 15-20 mins',
    firstTrip: '05:00',
    lastTrip: '22:00',
  },

  // --- Rail Lines ---
  {
    id: 'route_mrt3',
    name: 'MRT-3 Metro Rail Transit',
    mode: 'mrt',
    operator: 'DOTr MRT-3',
    frequency: 'Every 4-7 mins',
    firstTrip: '04:36',
    lastTrip: '22:10',
  },
  {
    id: 'route_lrt1',
    name: 'LRT-1 Light Rail Transit',
    mode: 'lrt',
    operator: 'Light Rail Manila Corporation',
    frequency: 'Every 3-5 mins',
    firstTrip: '04:30',
    lastTrip: '22:00',
  },
  {
    id: 'route_lrt2',
    name: 'LRT-2 Light Rail Transit',
    mode: 'lrt',
    operator: 'LRTA',
    frequency: 'Every 5-8 mins',
    firstTrip: '05:00',
    lastTrip: '21:30',
  },
  {
    id: 'route_walk_lrt1_mrt3_edsa',
    name: 'LRT-1 EDSA to MRT-3 Taft Footbridge Walkway',
    mode: 'walk',
    operator: 'Inter-station Walkway',
    frequency: 'Continuous',
  },
];

export const SEED_ROUTE_STOPS: RouteStop[] = [
  // --- route_jac_lucena_buendia ---
  {
    routeId: 'route_jac_lucena_buendia',
    stopOrder: 1,
    terminalId: 'term_lucena_grand',
    terminalName: 'Lucena Grand Central Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_jac_lucena_buendia',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 160,
    travelTimeMinutes: 110,
  },
  {
    routeId: 'route_jac_lucena_buendia',
    stopOrder: 3,
    terminalId: 'term_alabang_vtx',
    terminalName: 'VTX Starmall Alabang Terminal',
    fareEstimate: 230,
    travelTimeMinutes: 160,
  },
  {
    routeId: 'route_jac_lucena_buendia',
    stopOrder: 4,
    terminalId: 'term_buendia_gil_puyat',
    terminalName: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    fareEstimate: 270,
    travelTimeMinutes: 210,
  },

  // --- route_dltb_lucena_buendia ---
  {
    routeId: 'route_dltb_lucena_buendia',
    stopOrder: 1,
    terminalId: 'term_lucena_grand',
    terminalName: 'Lucena Grand Central Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_dltb_lucena_buendia',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 160,
    travelTimeMinutes: 110,
  },
  {
    routeId: 'route_dltb_lucena_buendia',
    stopOrder: 3,
    terminalId: 'term_buendia_gil_puyat',
    terminalName: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    fareEstimate: 270,
    travelTimeMinutes: 210,
  },

  // --- route_dltb_lucena_pitx ---
  {
    routeId: 'route_dltb_lucena_pitx',
    stopOrder: 1,
    terminalId: 'term_lucena_grand',
    terminalName: 'Lucena Grand Central Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_dltb_lucena_pitx',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 160,
    travelTimeMinutes: 110,
  },
  {
    routeId: 'route_dltb_lucena_pitx',
    stopOrder: 3,
    terminalId: 'term_alabang_vtx',
    terminalName: 'VTX Starmall Alabang Terminal',
    fareEstimate: 220,
    travelTimeMinutes: 155,
  },
  {
    routeId: 'route_dltb_lucena_pitx',
    stopOrder: 4,
    terminalId: 'term_pitx',
    terminalName: 'Parañaque Integrated Terminal Exchange (PITX)',
    fareEstimate: 260,
    travelTimeMinutes: 195,
  },

  // --- route_jac_lucena_cubao ---
  {
    routeId: 'route_jac_lucena_cubao',
    stopOrder: 1,
    terminalId: 'term_lucena_grand',
    terminalName: 'Lucena Grand Central Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_jac_lucena_cubao',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 160,
    travelTimeMinutes: 110,
  },
  {
    routeId: 'route_jac_lucena_cubao',
    stopOrder: 3,
    terminalId: 'term_alabang_vtx',
    terminalName: 'VTX Starmall Alabang Terminal',
    fareEstimate: 230,
    travelTimeMinutes: 160,
  },
  {
    routeId: 'route_jac_lucena_cubao',
    stopOrder: 4,
    terminalId: 'term_cubao_bus',
    terminalName: 'Cubao Bus Terminals (EDSA Araneta)',
    fareEstimate: 285,
    travelTimeMinutes: 240,
  },

  // --- route_jam_batangas_buendia ---
  {
    routeId: 'route_jam_batangas_buendia',
    stopOrder: 1,
    terminalId: 'term_batangas_grand',
    terminalName: 'Batangas City Grand Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_jam_batangas_buendia',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 110,
    travelTimeMinutes: 60,
  },
  {
    routeId: 'route_jam_batangas_buendia',
    stopOrder: 3,
    terminalId: 'term_alabang_vtx',
    terminalName: 'VTX Starmall Alabang Terminal',
    fareEstimate: 175,
    travelTimeMinutes: 90,
  },
  {
    routeId: 'route_jam_batangas_buendia',
    stopOrder: 4,
    terminalId: 'term_buendia_gil_puyat',
    terminalName: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    fareEstimate: 215,
    travelTimeMinutes: 120,
  },

  // --- route_alps_batangas_pitx ---
  {
    routeId: 'route_alps_batangas_pitx',
    stopOrder: 1,
    terminalId: 'term_batangas_grand',
    terminalName: 'Batangas City Grand Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_alps_batangas_pitx',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 110,
    travelTimeMinutes: 60,
  },
  {
    routeId: 'route_alps_batangas_pitx',
    stopOrder: 3,
    terminalId: 'term_pitx',
    terminalName: 'Parañaque Integrated Terminal Exchange (PITX)',
    fareEstimate: 205,
    travelTimeMinutes: 115,
  },

  // --- route_alps_batangas_cubao ---
  {
    routeId: 'route_alps_batangas_cubao',
    stopOrder: 1,
    terminalId: 'term_batangas_grand',
    terminalName: 'Batangas City Grand Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_alps_batangas_cubao',
    stopOrder: 2,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 110,
    travelTimeMinutes: 60,
  },
  {
    routeId: 'route_alps_batangas_cubao',
    stopOrder: 3,
    terminalId: 'term_cubao_bus',
    terminalName: 'Cubao Bus Terminals (EDSA Araneta)',
    fareEstimate: 235,
    travelTimeMinutes: 140,
  },

  // --- route_calamba_buendia ---
  {
    routeId: 'route_calamba_buendia',
    stopOrder: 1,
    terminalId: 'term_turbina_calamba',
    terminalName: 'Turbina Bus Terminal (Calamba)',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_calamba_buendia',
    stopOrder: 2,
    terminalId: 'term_alabang_vtx',
    terminalName: 'VTX Starmall Alabang Terminal',
    fareEstimate: 65,
    travelTimeMinutes: 40,
  },
  {
    routeId: 'route_calamba_buendia',
    stopOrder: 3,
    terminalId: 'term_buendia_gil_puyat',
    terminalName: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    fareEstimate: 105,
    travelTimeMinutes: 75,
  },

  // --- route_jeep_buendia_ayala ---
  {
    routeId: 'route_jeep_buendia_ayala',
    stopOrder: 1,
    terminalId: 'term_buendia_gil_puyat',
    terminalName: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_jeep_buendia_ayala',
    stopOrder: 2,
    terminalId: 'term_ayala_mrt',
    terminalName: 'MRT-3 Ayala Station / SM Makati / One Ayala',
    fareEstimate: 15,
    travelTimeMinutes: 22,
  },

  // --- route_edsa_carousel ---
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 1,
    terminalId: 'term_pitx',
    terminalName: 'Parañaque Integrated Terminal Exchange (PITX)',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 2,
    terminalId: 'term_mrt3_taft_ave',
    terminalName: 'MRT-3 Taft Avenue Station',
    fareEstimate: 15,
    travelTimeMinutes: 12,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 3,
    terminalId: 'term_ayala_mrt',
    terminalName: 'MRT-3 Ayala Station / SM Makati / One Ayala',
    fareEstimate: 35,
    travelTimeMinutes: 32,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 4,
    terminalId: 'term_mrt3_buendia',
    terminalName: 'MRT-3 Buendia Station',
    fareEstimate: 38,
    travelTimeMinutes: 37,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 5,
    terminalId: 'term_mrt3_guadalupe',
    terminalName: 'MRT-3 Guadalupe Station',
    fareEstimate: 40,
    travelTimeMinutes: 42,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 6,
    terminalId: 'term_mrt3_ortigas',
    terminalName: 'MRT-3 Ortigas Station',
    fareEstimate: 46,
    travelTimeMinutes: 55,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 7,
    terminalId: 'term_cubao_bus',
    terminalName: 'Cubao Bus Terminals (EDSA Araneta)',
    fareEstimate: 53,
    travelTimeMinutes: 68,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 8,
    terminalId: 'term_mrt3_quezon_ave',
    terminalName: 'MRT-3 Quezon Avenue Station',
    fareEstimate: 61,
    travelTimeMinutes: 82,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 9,
    terminalId: 'term_mrt3_north_ave',
    terminalName: 'MRT-3 North Avenue Station',
    fareEstimate: 65,
    travelTimeMinutes: 90,
  },
  {
    routeId: 'route_edsa_carousel',
    stopOrder: 10,
    terminalId: 'term_lrt1_monumento',
    terminalName: 'LRT-1 Monumento Station',
    fareEstimate: 75,
    travelTimeMinutes: 105,
  },

  // --- route_bus_alabang_ayala ---
  {
    routeId: 'route_bus_alabang_ayala',
    stopOrder: 1,
    terminalId: 'term_alabang_vtx',
    terminalName: 'VTX Starmall Alabang Terminal',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_bus_alabang_ayala',
    stopOrder: 2,
    terminalId: 'term_ayala_mrt',
    terminalName: 'MRT-3 Ayala Station / SM Makati / One Ayala',
    fareEstimate: 65,
    travelTimeMinutes: 40,
  },

  // --- route_mrt3 ---
  {
    routeId: 'route_mrt3',
    stopOrder: 1,
    terminalId: 'term_mrt3_north_ave',
    terminalName: 'MRT-3 North Avenue Station',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 2,
    terminalId: 'term_mrt3_quezon_ave',
    terminalName: 'MRT-3 Quezon Avenue Station',
    fareEstimate: 13,
    travelTimeMinutes: 4,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 3,
    terminalId: 'term_cubao_bus',
    terminalName: 'Cubao Bus Terminals (EDSA Araneta)',
    fareEstimate: 16,
    travelTimeMinutes: 9,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 4,
    terminalId: 'term_mrt3_ortigas',
    terminalName: 'MRT-3 Ortigas Station',
    fareEstimate: 20,
    travelTimeMinutes: 16,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 5,
    terminalId: 'term_mrt3_shaw',
    terminalName: 'MRT-3 Shaw Boulevard Station',
    fareEstimate: 20,
    travelTimeMinutes: 19,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 6,
    terminalId: 'term_mrt3_guadalupe',
    terminalName: 'MRT-3 Guadalupe Station',
    fareEstimate: 24,
    travelTimeMinutes: 24,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 7,
    terminalId: 'term_mrt3_buendia',
    terminalName: 'MRT-3 Buendia Station',
    fareEstimate: 24,
    travelTimeMinutes: 27,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 8,
    terminalId: 'term_ayala_mrt',
    terminalName: 'MRT-3 Ayala Station / SM Makati / One Ayala',
    fareEstimate: 28,
    travelTimeMinutes: 30,
  },
  {
    routeId: 'route_mrt3',
    stopOrder: 9,
    terminalId: 'term_mrt3_taft_ave',
    terminalName: 'MRT-3 Taft Avenue Station',
    fareEstimate: 28,
    travelTimeMinutes: 35,
  },

  // --- route_lrt1 ---
  {
    routeId: 'route_lrt1',
    stopOrder: 1,
    terminalId: 'term_lrt1_fpj',
    terminalName: 'LRT-1 Fernando Poe Jr. (Roosevelt) Station',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 2,
    terminalId: 'term_lrt1_monumento',
    terminalName: 'LRT-1 Monumento Station',
    fareEstimate: 15,
    travelTimeMinutes: 6,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 3,
    terminalId: 'term_lrt1_djose',
    terminalName: 'LRT-1 Doroteo Jose Station',
    fareEstimate: 25,
    travelTimeMinutes: 18,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 4,
    terminalId: 'term_lrt1_central',
    terminalName: 'LRT-1 Central Terminal Station',
    fareEstimate: 28,
    travelTimeMinutes: 24,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 5,
    terminalId: 'term_buendia_gil_puyat',
    terminalName: 'Buendia Bus Terminal (Gil Puyat & Taft)',
    fareEstimate: 35,
    travelTimeMinutes: 32,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 6,
    terminalId: 'term_lrt1_edsa',
    terminalName: 'LRT-1 EDSA Station',
    fareEstimate: 40,
    travelTimeMinutes: 37,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 7,
    terminalId: 'term_lrt1_baclaran',
    terminalName: 'LRT-1 Baclaran Station',
    fareEstimate: 43,
    travelTimeMinutes: 41,
  },
  {
    routeId: 'route_lrt1',
    stopOrder: 8,
    terminalId: 'term_lrt1_dr_santos',
    terminalName: 'LRT-1 Dr. Santos (Sucat) Station',
    fareEstimate: 50,
    travelTimeMinutes: 52,
  },

  // --- route_lrt2 ---
  {
    routeId: 'route_lrt2',
    stopOrder: 1,
    terminalId: 'term_lrt2_recto',
    terminalName: 'LRT-2 Recto Station',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_lrt2',
    stopOrder: 2,
    terminalId: 'term_cubao_bus',
    terminalName: 'Cubao Bus Terminals (EDSA Araneta)',
    fareEstimate: 23,
    travelTimeMinutes: 18,
  },
  {
    routeId: 'route_lrt2',
    stopOrder: 3,
    terminalId: 'term_lrt2_antipolo',
    terminalName: 'LRT-2 Antipolo Station',
    fareEstimate: 33,
    travelTimeMinutes: 38,
  },

  // --- route_walk_lrt1_mrt3_edsa ---
  {
    routeId: 'route_walk_lrt1_mrt3_edsa',
    stopOrder: 1,
    terminalId: 'term_lrt1_edsa',
    terminalName: 'LRT-1 EDSA Station',
    fareEstimate: 0,
    travelTimeMinutes: 0,
  },
  {
    routeId: 'route_walk_lrt1_mrt3_edsa',
    stopOrder: 2,
    terminalId: 'term_mrt3_taft_ave',
    terminalName: 'MRT-3 Taft Avenue Station',
    fareEstimate: 0,
    travelTimeMinutes: 5,
  },
];

export const SEED_HUBS: TransferHub[] = [
  {
    id: 'hub_buendia_ayala',
    hubName: 'Buendia (Gil Puyat) to Ayala Ave / SM Makati Transfer',
    connectingModes: ['bus', 'jeepney', 'mrt'],
    walkingTimeMinutes: 4,
    tips: 'From Buendia bus terminals (Taft/Gil Puyat), walk out to Sen. Gil Puyat Ave. Board an Ayala or Washington jeepney/city bus heading directly to Ayala Ave / SM Makati. Alternatively, take LRT-1 Gil Puyat south to EDSA Station and transfer via the walkway to MRT-3 Taft Ave towards Ayala Station.',
  },
  {
    id: 'hub_pitx_carousel',
    hubName: 'PITX EDSA Carousel Busway Transfer',
    connectingModes: ['bus'],
    walkingTimeMinutes: 4,
    tips: 'At PITX, proceed to Gate 10 on the Ground Floor (Bay 10) to board the EDSA Carousel Busway directly to One Ayala / SM Makati.',
  },
  {
    id: 'hub_edsa_taft_interchange',
    hubName: 'LRT-1 EDSA <-> MRT-3 Taft Avenue Interchange',
    connectingModes: ['lrt', 'mrt'],
    walkingTimeMinutes: 5,
    tips: 'Use the elevated connecting walkway between LRT-1 EDSA Station and MRT-3 Taft Avenue Station without exiting to street level.',
  },
  {
    id: 'hub_cubao_interchange',
    hubName: 'Cubao Transit Interchange (Provincial Buses, MRT-3, LRT-2, EDSA Carousel)',
    connectingModes: ['bus', 'mrt', 'lrt'],
    walkingTimeMinutes: 8,
    tips: 'Cubao connects provincial bus terminals along EDSA to MRT-3 Araneta Center-Cubao Station and LRT-2 via Farmers Plaza and Gateway Mall walkways.',
  },
  {
    id: 'hub_alabang_oneayala',
    hubName: 'Alabang VTX Express to One Ayala',
    connectingModes: ['bus'],
    walkingTimeMinutes: 3,
    tips: 'Board the express city or P2P bus at Starmall / VTX Alabang taking the Skyway directly to One Ayala Terminal.',
  },
];
